site_name: Wireless Review

theme:
  name: material

nav:
  - Home: index.md

  - Wireless Communications:
      - Maxwell's Equation: wireless/Maxwells_equations.md
      - Fading Channel Types: wireless/fading_types_summary.md
      - Shannon Capacity: wireless/shannon.md
      - Link Budget: wireless/link_budget.md
      - Modulation Techniques: wireless/modulation.md
      - MU-MIMO Detectors: wireless/multiusermimodetectors.md
      - OFDM: wireless/ofdm.md
      - Waterfilling Concept: wireless/Waterfilling.md
      - OFDM Channel Estimation: wireless/ChannelEstimation.md
      - OFDM Channel Equalization: wireless/Channel_Equalization.md
      - Implementation Imperfactions: wireless/implementationImperfections.md
extra_css:
  - styles/extra.css


markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.tasklist
plugins:
  - search
  - mermaid2
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js