site_name: Wireless Interview Guide

theme:
  name: material

nav:
  - Home: index.md

  - Wireless Communications:
      - Maxwell's Equation: wireless/Maxwells_equations.md
      - Fading Channel Types: wireless/fading_types_summary.md
      - Shannon Capacity: wireless/shannon.md
      - Link Budget: wireless/link_budget.md
      - Modulation Techniques: wireless/modulation.md
      - MU-MIMO Detectors: wireless/multiusermimodetectors.md
      - OFDM: wireless/ofdm.md
      - Waterfilling Concept: wireless/Waterfilling.md
      - OFDM Channel Estimation: wireless/ChannelEstimation.md
      - OFDM Channel Equalization: wireless/Channel_Equalization.md
      - Implementation Imperfactions: wireless/implementationImperfections.md

  - Estimation Theory:
      - MMSE and ML Estimators: estimation/mmse_ml.md
      - Kalman Filter: estimation/kalman_filter.md
      - Noise Models: estimation/noise_models.md

  - Discrete Time Signal Processing:
      - CTFT, DTFT, DFT: dsp/FT.md
      - DFT and FFT: dsp/dft_fft.md
      - Circular Convolution: dsp/circ_conv.md
      - Filters (FIR/IIR,Polyphase): dsp/filters.md
      - Sampling Theorem: dsp/sampling.md
  - RF Tranceiver Front-end:
    - Basics: RF_Tranceiver/Basics.md
    - Overview.: RF_Tranceiver/BasicTranceiver_circuit.md
    - Receiver Arch.: RF_Tranceiver/ReceiverArch.md
    - I-Q Inbalance: RF_Tranceiver/I_Q_Inbalance.md
    - Phase Noise: RF_Tranceiver/phase_noise.md
    - SSB vs DSB: RF_Tranceiver/SSBvsDSB.md
    - Impedence Matching: RF_Tranceiver/Sparameters.md
  - Measurement and Test:
      - RF Measurment Overview: tools/RF_WLAN_Measurement_Overview.md
      - Spectrum Analyzer: tools/spectrum_analyzer.md
      - EVM vs Modulation: tools/evm_vs_modulation.md
      - Active vs Passive Probe: tools/active_probe.md

  - Wi-Fi Standards:
      - 802.11a/b/g/n/ac/ax Summary: wifi/standards_overview.md
      - OFDMA & MU-MIMO: wifi/ofdma_mu_mimo.md
      - Uplink/Downlink Scheduling: wifi/uplink_downlink.md
  - Programming:
    - CPP Basic Concepts: programming/CPP_Basics.md
    - Stack vs Heap: programming/stackvsheap.md
    - CPP vs Python Elements: programming/dict_CPP.md
    - Coding Practice: programming/programming_progress.html
  - Interviw Questions: 
    - Basic RF QUestion: InterviewQuestions/interview_rf_basic_questions.md
  - Common Interview Questions: 
      - Common Interview Topics: InterviewQuestions/FAQTOPICS.md
      - Top Questions (Glassdoor): InterviewQuestions/Top_Questions.md

  - Quiz: quiz.html
  - Progress Tracker: progress.md

extra_css:
  - styles/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - attr_list
  - pymdownx.tasklist
plugins:
  - search
  - mermaid2
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js