name: Manual Deploy MkDocs to gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to gh-pages branch manually
        run: |
          cd site
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hhosseinian/WirelessReview.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy MkDocs site"
          git push --force origin gh-pages
