name: Deploy MkDocs with Mermaid Diagrams

on:
  push:
    branches: [main]  # or 'master' if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/hhosseinian/WirelessReview

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
